app = "barbara-voice-bridge"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = 8080
NODE_ENV = "production"
USE_WEBRTC = "true"

[experimental]
auto_rollback = true

# TCP service for the bridge server with HTTPS
[[services]]
protocol = "tcp"
internal_port = 8080

  [[services.ports]]
  port = 80
  handlers = ["http"]
  
  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]

# UDP services for WebRTC (when USE_WEBRTC=true)
[[services]]
protocol = "udp"
internal_port = 3478
  [[services.ports]]
  port = 3478

[[services]]
protocol = "udp"
internal_port = 5349
  [[services.ports]]
  port = 5349

# WebRTC media ports (for audio streaming)
[[services]]
protocol = "udp"
internal_port = 10000
  [[services.ports]]
  port = 10000

[[services]]
protocol = "udp"
internal_port = 20000
  [[services.ports]]
  port = 20000
