# fly.toml - Barbara Voice Assistant V3
app = "barbara-v3-voice"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8080"
  LOG_LEVEL = "info"
  AUDIO_FORMAT = "g711_ulaw"
  OPENAI_REALTIME_MODEL = "gpt-4o-realtime-preview"

