name: Deploy Barbara V2 (RELAY SDK)

on:
  push:
    branches: [main]
    paths: ['barbara-v2/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest
          
      - name: Deploy Barbara V2
        run: flyctl deploy --config barbara-v2/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
      - name: Verify deployment
        run: |
          echo "✅ Barbara V2 deployed successfully"
          echo "App: barbara-v2-relay"
          echo "Health check: https://barbara-v2-relay.fly.dev/health"
