name: Deploy Barbara V1 (WebSocket)

on:
  push:
    branches: [main]
    paths: ['barbara-v1/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest
          
      - name: Deploy Barbara V1
        run: flyctl deploy --config barbara-v1/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
      - name: Verify deployment
        run: |
          echo "✅ Barbara V1 deployed successfully"
          echo "App: barbara-voice-bridge"
          echo "Health check: https://barbara-voice-bridge.fly.dev/healthz"
